### ISSUE TITLE
fe_assets_message load for cn 

### ISSUE THREAD

**Issue by rocklightL** [thane98/Astra#7]
fe_assets_message load for cn shall be cn/cnch,
while the update astra-v0.3.0 or v0.3.1 use ch/cnch,
a little bit different.it caused project failed to load
![无标题](https://github.com/thane98/Astra/assets/170909222/3d6d277d-8550-4a60-9d0f-515ae3dfb13e)

**Comment by thane98** [comment]
Hey, sorry about this. I've updated v0.3.1 with a fix for the Chinese localization path: https://github.com/thane98/Astra/releases/tag/v0.3.1

Let me know if that fixes your issue.
